### ISSUE TITLE
Notification Channel missing items

### ISSUE THREAD

**Issue by smasher816** [Beepiz/BleGattCoroutines#12]
First of all, awesome library. Thank you so much for simplifying my bluetooth callback and handling code.

After enabling notifications and writing to the cccd as described here https://github.com/Beepiz/BleGattCoroutines/issues/5#issuecomment-355335034 I do sucessfully get notifications. However I discovered that notifications are sometimes not processed. Using the code below a log message seems to consistently only be produced for every other notification sent from the device.
```
notifyChannel.consumeEach {
    Log.i("BLEService", "notification: ${it.uuid} => ${it.value.toHexString()}")
}
```

Using the "nRF Connect" app every notification is received and displayed, so it does not appear to be a device/firmware issue.

**Comment by LouisCAD** [comment]
Hi @smasher816, thanks for the kind words.
Do you listen to the `stateChangeChannel` to watch for potential errors or connection loss? Also, is nRF Connect active in the background when you encounter this issue?

**Comment by smasher816** [comment]
Hi @LouisCAD, I have been using the `GattConnection.logConnectionChanges()` function and have not seen any connection losses. nRF Connect has been closed and was only used after.

With a bit more testing this only seems to happen when requesting notifications for one characteristic, and then later requesting notifications for another.

```
enableNotifications(characteristic1Uuid)
write(characteristic1Uuid)
notifyChannel
    .filter{ c -> c.uuid == characteristic1Uuid }
    .receive()
 /* .... */
enableNotifications(characteristic2Uuid)
write(characteristic2Uuid)
notifyChannel
    .filter{ c -> c.uuid == characteristic2Uuid }
    //.receive()
    .consumeEach { Log.i("BLEService", "notification: ${it.uuid} => ${it.value.toHexString()}") }
```

Strangely enough characteristic2 is only messed up if there is only a single notification for characteristic1. If characteristic1 sends two notifications then every notification for characteristic2 is then received correctly. I tried reading and writing to the characteristics in the same order with the nordic app  and was not able to reproduce this oddity.

If I manage to get ahold of a ble packet sniffer in the coming days I will try to upload a log of what exactly is being transmitted over the air

**Comment by LouisCAD** [comment]
The issue here is that by calling `receive()` on the `notifyChannel`, you suspend the coroutine until a notification is received. That means you don't reach the point where you subscribe to the other notification until a first one is received.

What you should do instead is adding a subscriber to the `notifyChannel` by calling `consumeEach { ... }` before applying any filter, and if you don't want to suspend the coroutine, do it in another coroutine (that you launch using `launch(coroutineContext)` or `async(coroutineContext)`.

**Comment by LouisCAD** [comment]
@smasher816 Can you confirm that writing a descriptor is **required** in order to receive notifications, as stated in #5?

**Comment by smasher816** [comment]
I do actually mean for the coroutine to suspend. My ble device has a kind of call and response architecture where the phone can pass it data, wait for human interaction, then compute a result and pass it back to the phone with a notification.

I have the `enableNotifications, write, notifyChannel.receive()` process above wrapped in a function called `writeAndReadResponse`. If I call `var foo = writeAndReadResponse(char1)`, then foo is set after the first notification sent from the device. If I then later want to compute another result and call `var bar = writeAndReadResponse(char2)` then the next notification sent from the device is ignored and it is not until I modify the code to send two notifications that the receive returns and bar is set. Sorry if that is a bit confusing.

I'll test #5 later today, but I know that before I migrated to your library I definitely had to write to the descriptor. Just calling BluetoothGatt.setCharacteristicNotificationsEnabled was not enough. See https://stackoverflow.com/questions/22817005/why-does-setcharacteristicnotification-not-actually-enable-notifications

**Comment by LouisCAD** [comment]
Thanks for the link. It seems the `setCharacteristicNotification(…)` method only allows the Android device to receive notifications, but it doesn't mean they are enabled on the other side. That's probably the cause of your issue.

I commented in #5 on what we can expect in next version to address this.

**Comment by LouisCAD** [comment]
This may have been caused by the fact that `notifyChannel` was not a `BroadcastChannel`. Version 0.4.0 just released should resolve your issue, and also brings a new `openNotificationSubscription` function that may be a better fit for what you want.
