### ISSUE TITLE
Add isConnected property on GattConnection

### ISSUE THREAD

**Issue by LouisCAD** [Beepiz/BleGattCoroutines#17]

**Comment by bj0** [comment]
doesn't this already exist?
https://github.com/Beepiz/BleGattCoroutines/blob/master/core/src/main/java/com/beepiz/bluetooth/gattcoroutines/experimental/GattConnection.kt#L78

I came here because this property is not being correctly updated when the BLE connection drops (turn device off).

**Comment by LouisCAD** [comment]
You're right @bj0, it already exists! I forgot it I had already added it. You say it's not being updated correctly… Does the `stateChangeChannel` receives any disconnection value?

**Comment by bj0** [comment]
it does receive a `newState`, but the `status` flag is `8` when it happens, so it bypasses the `when` check.

I can't find `8` in the android docs, so i'm not sure what it means.

**Comment by LouisCAD** [comment]
@bj0 Out of curiosity, what device, running which version of Android are you using that gives you an `8` status?
Also, this may be an error code returned by the BLE device, you can check if in the same conditions but on a different device, you get the same status code

**Comment by bj0** [comment]
It's a Samsung S7.  I don't think it comes from the BLE device as I get it several seconds after i turn the BLE device off.  I am assuming it has something to do with the connection timing out.

**Comment by LouisCAD** [comment]
Strange...
