### ISSUE TITLE
Prevent GattConnection re-use

### ISSUE THREAD

**Issue by bj0** [Beepiz/BleGattCoroutines#18]
I've been having issues with disconnecting and then reconnecting a `GattConnection` device.  It reconnects fine, but a lot of functionality stops working.  Sends are timing out, and notifications no longer come.  

Have you been able to get this to work properly?

Note if I `close` the device and create a new one everything works fine.

**Comment by LouisCAD** [comment]
I've been thinking about how it would really work when the connection is dropped, then made again, when reusing the same `GattConnection` instance, and I'm wondering if I should really reuse it.
I'm not sure if I should make it optional, or completely remove the reusability.
If it worked properly, would reusing the `GattConnection` after a disconnection really help your use case, or you can as well create a new one and redo and resume the work you need?

**Comment by LouisCAD** [comment]
On a BLE device type i'm currently working on, some state is reset on each new connection, and I observed dead suspensions too. To alleviate this issue, I launched a coroutine that consumes the `stateChangeChannel` and closes the `GattConnection` on any disconnection, so it fails, and I redo the work from a clean state.

**Comment by bj0** [comment]
I'm not sure if it saves anything to re-use the connection.  I assumed it would be more efficient than recreating it every time, but since it's not working properly I'll probably just re-create it on `connect()` calls.

I wrap it all in my own `ConnectionManager` object anyway to maintain persistent channels between devices, which is the only issue I can see in recreating the device each time.

**Comment by LouisCAD** [comment]
I changed the title. This will be worked on.

**Comment by LouisCAD** [comment]
This has been fixed in version 0.2.0-rc01.
