### ISSUE TITLE
Support more connection parameters like autoConnect, transport and phy

### ISSUE THREAD

**Issue by LouisCAD** [Beepiz/BleGattCoroutines#21]
Mind the API level requirements while implementing this

**Comment by Miha-x64** [comment]
One more thing to know: while [GattConnectionImpl uses](https://github.com/Beepiz/BleGattCoroutines/blob/master/core/src/main/java/com/beepiz/bluetooth/gattcoroutines/experimental/GattConnectionImpl.kt#L225) direct connection, [it also calls](https://github.com/Beepiz/BleGattCoroutines/blob/master/core/src/main/java/com/beepiz/bluetooth/gattcoroutines/experimental/GattConnectionImpl.kt#L76) [BluetoothGatt.connect()](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/bluetooth/BluetoothGatt.java#915) which internally establishes 'auto-connected' (i. e. non-direct) connection via [internal API](https://android.googlesource.com/platform/frameworks/base/+/0e2d281/core/java/android/bluetooth/IBluetoothGatt.aidl#38).
For more info, see [this SO answer](https://stackoverflow.com/a/40187086/3050249).

**Comment by LouisCAD** [comment]
I can't believe they allowed such code into AOSP with so poor documentation…
Thank you for making me aware of this, will help next time I spend some time on this issue and other related issues.
