### ISSUE TITLE
minSdk / @RequiresApi

### ISSUE THREAD

**Issue by Miha-x64** [Beepiz/BleGattCoroutines#25]
Hello.
I can see many methods with `@RequiresApi(18)` (which is a version when BLE support was added). Is there any reason for library to have `minSdk 14`?

**Comment by LouisCAD** [comment]
Hello, yes there's good reason.
Do you know what would happen to all apps using this library if I raised the minSdk to 18, and removed the annotations?

Here's what would happen:
1. The apps that support an SDK lower than 18 would no longer compile with the new version.
2. They would circumvent this restriction by forcing library minSdk override.
3. Then, when writing new code, there would be no warning when using the library without checking the SDK, which would lead to crashes.

So the minSdk will stay at 14, unless nearly no one makes apps supporting API 14 (at which point, AndroidX would probably have raised its minSdk).
