### ISSUE TITLE
Update Readme to mention allow reconnect

### ISSUE THREAD

**Issue by bj0** [Beepiz/BleGattCoroutines#34]
The example in the Readme shows using `disconnect()`, but if you try to use it you get an exception:

```java.lang.IllegalArgumentException: Disconnect is not supported when auto connect is not allowed. Use close() instead.```

No where in the readme or examples is there anything about any "auto connect".  I only found it by digging through the code.

**Comment by LouisCAD** [comment]
You're right, this line of code should be removed from the README. Do you
want to submit a PR directly on master for this?
