### ISSUE TITLE
Publish the library on jcenter

### ISSUE THREAD

**Issue by LouisCAD** [Beepiz/BleGattCoroutines#4]
Should be done ASAP this month

**Comment by bj0** [comment]
You may want to add to your download comment "but it's made of only 4 Kotlin files, so you can already try it out in your project pretty easily."  That it also uses another one of your libraries and how to get it, otherwise you have to dig through your project looking at build.gradle files.

**Comment by LouisCAD** [comment]
I agree, I will edit the doc today. Thanks for your comment!
Sent with Android 8.1

**Comment by LouisCAD** [comment]
@bj0 I just edited download instructions in the README to avoid any future confusion.

**Comment by LouisCAD** [comment]
More than a month late, but will come soon. Likely the coming week

**Comment by LouisCAD** [comment]
Version 0.1.0 is published on bintray! Sync to jcenter has been requested and is pending.

In the meantime, you can add the bintray repo to the `repositories` closure in your `build.gradle`:
`maven { url  "https://dl.bintray.com/beepiz/maven" }`,
and use the dependencies right now:
`implementation 'com.beepiz.blegattcoroutines:blegattcoroutines-core:0.1.0'`
`implementation 'com.beepiz.blegattcoroutines:blegattcoroutines-genericaccess:0.1.0'`

**Comment by LouisCAD** [comment]
jcenter sync complete! 🎉 🎉
The Download instructions in the README have been updated.
