### ISSUE TITLE
How to catch fatal disconnect?

### ISSUE THREAD

**Issue by MikhailNatalenko** [Beepiz/BleGattCoroutines#49]
It's a little bit strange, but I do not catch anything from BLE if I disconnect it hardly. For example, if I switch the device off. Or if I turn off Bluetooth on my phone. I do catch everything if I disconnect from phone "properly".

So for example, if I connect the phone to the device and then reset the device - nothing will happen until I'll try to send something.

**Comment by MikhailNatalenko** [comment]
Another simple case: connect to ble, and then just switch Bluetooth off.

**Comment by MikhailNatalenko** [comment]
It looks like I don't set timeout. Is it possible?

**Comment by LouisCAD** [comment]
> It looks like I don't set timeout. Is it possible?

I'm not sure what you mean here. Only you can know if you set timeout or not. Also, it's unclear to me what you're talking about when you ask if it is possible.

**Comment by LouisCAD** [comment]
Fixed formatting of my comment above.
Is there a reason why you closed it without telling why?

**Comment by MikhailNatalenko** [comment]
Sorry, I was a little bit busy. To be honest, I don't even remember exactly the point of this issue, I'm not working with the library and the project anymore, so I'm not sure did I solve it by myself or not. Sorry again!
