### ISSUE TITLE
Update project

### ISSUE THREAD

**Issue by LouisCAD** [Beepiz/BleGattCoroutines#62]
1. Integrate [refreshVersions](https://github.com/jmfayard/refreshVersions)
2. Update dependencies with it
3. Replace exposed `Channel`s with `Flow`s
4. Review PRs, and merge the ones that are improvements giving no drawback, or build upon the idea to make something better
5. Release a new version

**Comment by Volatile-Memory** [comment]
![image](https://user-images.githubusercontent.com/2176942/77836117-5e68b000-7121-11ea-9ac2-b57f18baab4a.png)

When cloning this repo with the latest stable Android Studio, I get that prompt and the automatic upgrade fails:
![image](https://user-images.githubusercontent.com/2176942/77836134-7a6c5180-7121-11ea-8b4d-8470bbdda943.png)

Any ideas?

**Comment by francismariano** [comment]
Hello @LouisCAD 

Let us know about update project. Do you need help with something?

**Comment by LouisCAD** [comment]
Hi @francismariano thanks for offering help and sorry for the long time with no response.

I was sidetracked by other open source projects ([refreshVersions](https://github.com/jmfayard/refreshVersions) and [Splitties](https://github.com/LouisCAD/Splitties)) and life.

I'll get back to this project and update it soon, before Kotlin 1.4 Online Event, and going forward, it'll be updated more often where needed as I'll add a few things to ease maintenance on my side (refreshVersions and CI).

Thanks for your patience.

**Comment by LouisCAD** [comment]
Was much longer than I wanted, but now, the project has been updated. This issue is now obsolete 🙂
